name: Acceptance

on: 
    push: 
        tags:
            - v*

jobs:
    deploy:
        runs-on: ubuntu-20.04
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              with:
                fetch-depth: 5
                fetch-tags: true

            - name: git log
              run: git log

            - name: github.ref_name
              run: echo ${{ github.ref_name }}
            