name: Testing

on: 
    push: 
        branches: "main"

jobs:
    deploy:
        runs-on: ubuntu-20.04
        steps:
            - name: "Log github"
              run: echo ${{ github }}
            