name: Production

on: 
    push: 
        branches: 
            - main

jobs:
    deploy:
        runs-on: ubuntu-20.04
        steps:
            - name: checkout code
              uses: actions/checkout@v4
              with:
                fetch-depth: 5
                fetch-tags: true

            - name: git describe
              run: git describe --tags --abbrev=0

            - name: github.ref_name
              run: echo ${{ github.ref_name }}
            