name: Production

on: 
    push: 
        branches: 
            - main

jobs:
    deploy:
        runs-on: ubuntu-20.04
        steps:
            - name: "Log github"
              run: |
                TAG=$(git describe --abbrev=0)
                echo ${TAG}
            