name: Production

on: 
    push: 
        branches: 
            - main

jobs:
    deploy:
        runs-on: ubuntu-20.04
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: "git Describe Command"
              run: git describe --exact-match --tags $(git log -n 1 --pretty='%h')
              
            - name: "GitHub.ref_name"
              run: echo ${{ github.ref_name }}
            