name: Production

on: 
    push: 
        branches: 
            - main

jobs:
    deploy:
        runs-on: ubuntu-20.04
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              with:
                fetch-depth: 5

            - name: "git log"
              run: git log

            - name: "git describe"
              run: git describe --tags --abbrev=0

            - name: "GitHub.ref_name"
              run: echo ${{ github.ref_name }}
            